apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildando-a-aplicacao
spec:
  steps:
  - name: buildar
    image: alpine/git:v2.26.2
    script: |
      #!/usr/bin/env sh
      echo "Finja que estou buildando a aplicação aqui :D"
      echo "Opa, está buildado!"